#!/usr/bin/env bash
set -euo pipefail

# Idempotent Discord Channel + Webhook Setup for Axinova Agent Fleet
# Creates channels and webhooks via Discord REST API (skips if already exist)
#
# Required env vars:
#   DISCORD_BOT_TOKEN  - Bot token from Discord Developer Portal
#   DISCORD_SERVER_ID  - Guild/server ID (right-click server → Copy Server ID)
#
# Output: ~/.config/axinova/discord-webhooks.env
# Compatible with bash 3.x (macOS default)

DISCORD_API="https://discord.com/api/v10"
CONFIG_DIR="$HOME/.config/axinova"
ENV_FILE="$CONFIG_DIR/discord-webhooks.env"

# --- Validation ---

if [[ -z "${DISCORD_BOT_TOKEN:-}" ]]; then
  echo "Error: DISCORD_BOT_TOKEN not set"
  echo "Export it or pass it: DISCORD_BOT_TOKEN=xxx ./discord-setup.sh"
  exit 1
fi

if [[ -z "${DISCORD_SERVER_ID:-}" ]]; then
  echo "Error: DISCORD_SERVER_ID not set"
  echo "Export it or pass it: DISCORD_SERVER_ID=xxx ./discord-setup.sh"
  exit 1
fi

AUTH_HEADER="Authorization: Bot $DISCORD_BOT_TOKEN"

# --- Helper functions ---

discord_api() {
  local method="$1" endpoint="$2"
  shift 2
  local url="${DISCORD_API}${endpoint}"
  curl -sf -X "$method" "$url" \
    -H "$AUTH_HEADER" \
    -H "Content-Type: application/json" \
    "$@"
}

get_channels() {
  discord_api GET "/guilds/${DISCORD_SERVER_ID}/channels"
}

find_channel_id() {
  local channels="$1" name="$2"
  echo "$channels" | jq -r ".[] | select(.name == \"$name\") | .id" | head -1
}

create_channel() {
  local name="$1" type="${2:-0}" parent_id="${3:-}"
  local payload="{\"name\":\"$name\",\"type\":$type"
  if [[ -n "$parent_id" ]]; then
    payload+=",\"parent_id\":\"$parent_id\""
  fi
  payload+="}"
  discord_api POST "/guilds/${DISCORD_SERVER_ID}/channels" -d "$payload"
}

get_channel_webhooks() {
  local channel_id="$1"
  discord_api GET "/channels/${channel_id}/webhooks"
}

find_webhook_url() {
  local webhooks="$1" name="$2"
  echo "$webhooks" | jq -r ".[] | select(.name == \"$name\") | \"https://discord.com/api/webhooks/\\(.id)/\\(.token)\"" | head -1
}

create_webhook() {
  local channel_id="$1" name="$2"
  discord_api POST "/channels/${channel_id}/webhooks" \
    -d "{\"name\":\"$name\"}"
}

# Ensure or get a channel, print its ID
ensure_channel() {
  local channels="$1" name="$2" parent_id="$3"
  local existing_id
  existing_id=$(find_channel_id "$channels" "$name")
  if [[ -z "$existing_id" ]]; then
    echo "  Creating channel: #$name" >&2
    local response
    response=$(create_channel "$name" 0 "$parent_id")
    echo "$response" | jq -r '.id'
  else
    echo "  Channel #$name already exists ($existing_id)" >&2
    echo "$existing_id"
  fi
}

# Ensure or get a webhook, print its URL
ensure_webhook() {
  local ch_id="$1" wh_name="$2"
  local webhooks existing_url
  webhooks=$(get_channel_webhooks "$ch_id")
  existing_url=$(find_webhook_url "$webhooks" "$wh_name")
  if [[ -z "$existing_url" ]]; then
    echo "  Creating webhook '$wh_name'" >&2
    local response wh_id wh_token
    response=$(create_webhook "$ch_id" "$wh_name")
    wh_id=$(echo "$response" | jq -r '.id')
    wh_token=$(echo "$response" | jq -r '.token')
    echo "https://discord.com/api/webhooks/${wh_id}/${wh_token}"
  else
    echo "  Webhook '$wh_name' already exists" >&2
    echo "$existing_url"
  fi
}

# --- Main ---

echo "==> Discord Setup for Axinova Agent Fleet"
echo "    Server ID: $DISCORD_SERVER_ID"
echo ""

# Fetch existing channels
echo "→ Fetching existing channels..."
CHANNELS=$(get_channels)

# Step 1: Create category "Agent Fleet" if it doesn't exist
CATEGORY_ID=$(find_channel_id "$CHANNELS" "Agent Fleet")
if [[ -z "$CATEGORY_ID" ]]; then
  echo "  Creating category: Agent Fleet"
  CATEGORY_RESPONSE=$(create_channel "Agent Fleet" 4)
  CATEGORY_ID=$(echo "$CATEGORY_RESPONSE" | jq -r '.id')
else
  echo "  Category 'Agent Fleet' already exists ($CATEGORY_ID)"
fi

# Step 2: Create text channels under the category
echo ""
echo "→ Creating channels..."
ID_TASKS=$(ensure_channel "$CHANNELS" "agent-tasks" "$CATEGORY_ID")
ID_PRS=$(ensure_channel "$CHANNELS" "agent-prs" "$CATEGORY_ID")
ID_ALERTS=$(ensure_channel "$CHANNELS" "agent-alerts" "$CATEGORY_ID")
ID_LOGS=$(ensure_channel "$CHANNELS" "agent-logs" "$CATEGORY_ID")

# Step 3: Create webhooks for notification channels
echo ""
echo "→ Setting up webhooks..."
WH_PRS=$(ensure_webhook "$ID_PRS" "Axinova PR Bot")
WH_ALERTS=$(ensure_webhook "$ID_ALERTS" "Axinova Alert Bot")
WH_LOGS=$(ensure_webhook "$ID_LOGS" "Axinova Log Bot")

# Step 4: Write .env file
echo ""
echo "→ Writing webhook config to $ENV_FILE"
mkdir -p "$CONFIG_DIR"

cat > "$ENV_FILE" <<EOF
# Discord webhook URLs for Axinova Agent Fleet
# Generated by discord-setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Re-run discord-setup.sh to regenerate (idempotent)

DISCORD_WEBHOOK_PRS="$WH_PRS"
DISCORD_WEBHOOK_ALERTS="$WH_ALERTS"
DISCORD_WEBHOOK_LOGS="$WH_LOGS"
DISCORD_CHANNEL_TASKS="$ID_TASKS"
DISCORD_CHANNEL_PRS="$ID_PRS"
DISCORD_CHANNEL_ALERTS="$ID_ALERTS"
DISCORD_CHANNEL_LOGS="$ID_LOGS"
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "Done! Channel IDs and webhook URLs saved to $ENV_FILE"
echo ""
echo "Channels created:"
echo "  #agent-tasks → $ID_TASKS"
echo "  #agent-prs   → $ID_PRS"
echo "  #agent-alerts → $ID_ALERTS"
echo "  #agent-logs  → $ID_LOGS"
echo ""
echo "Test a webhook:"
echo "  source $ENV_FILE"
echo "  curl -H 'Content-Type: application/json' -d '{\"content\":\"Hello from setup!\"}' \$DISCORD_WEBHOOK_PRS"
